<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>FordNexus.Api</RootNamespace>
    <UserSecretsId>ford-nexus-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FordNexus.Application\FordNexus.Application.csproj" />
    <ProjectReference Include="..\FordNexus.Infrastructure\FordNexus.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FordNexus.Api.Tests" />
  </ItemGroup>
</Project>
